import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/custom/SideBar";
import ProfileHeading from "@/components/custom/ProfileHeading";

const workSans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const items = [
    {
      title: "Home",
      links: [
        { label: "Introduction", href: "#introduction" },
        { label: "About Me", href: "#about-me" },
      ],
    },
    {
      title: "Education",
      items: [
        {
          title: "Education",
          links: [
            { label: "University", href: "#" },
            { label: "Collage", href: "#" },
          ],
        },
        {
          title: "Subsection 1.2",
          items: [
            {
              title: "Sub-subsection 1.2.1",
              links: [
                { label: "Link 1.2.1.1", href: "#" },
                { label: "Link 1.2.1.2", href: "#" },
              ],
            },
          ],
        },
      ],
    },
    {
      title: "Section 2",
      links: [
        { label: "Link 2.1", href: "#" },
        { label: "Link 2.2", href: "#" },
      ],
    },
  ];
  return (
    <html lang="en">
      <body className={workSans.className}>
        <div className="flex ">
          <Sidebar items={items} />
          <div className="flex-1 px-4 md:px-8 lg:px-16  mt-16 md:mt-8 w-full">
            <ProfileHeading/>
            <div className="mt-8 md:mt-4">{children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
