import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import Sidebar, { SidebarItem } from "@/components/custom/SideBar";
import ProfileHeading from "@/components/custom/ProfileHeading";

const workSans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const items: SidebarItem[] = [
    {
      title: "Home",
      href: "/",
      links: [
        {
          label: "Introduction",
          href: "/#introduction",
        },
        {
          label: "About Me",
          href: "/#about-me",
        },
      ],
    },
    {
      title: "Education",
      href:"education",
      links: [
        { label: "Education", href: "education/#education" },
        { label: "International Certification", href: "education/#international-certification" },
        { label: "Online Coureses", href: "education/#Online-Coureses" },
        { label: "Training & WorkShop", href: "education/#training" },
      ],
    },
    {
      title: "Experience",
      href:"/work-experience",
      links: [
        { label: "Professional-Experience", href: "/work-experience#professional-experience" },
        { label: "Research Experience", href: "/work-experience#research-experience" },
        { label: "Teaching Experience", href: "/work-experience#teaching-experience" },
      ],
    },
    {
      title:"Research",
      href:"/publications",
      links:[
        {href:"/publications#peer-reviewed-conference",label:"Peer Reviewed Conference"},
        {href:"/publications#book-chapter",label:"Book Chapter"},
        {href:"/publications#in-progress",label:"In Progress"}
      ]
    },
    {title:'Projects',
      href:"/projects"
    }
  ];
  return (
    <html lang="en">
      <body className={workSans.className}>
        <div className="flex ">
          <Sidebar items={items} />
          <div className="flex-1 px-4 md:px-8 lg:px-16  mt-16 md:mt-8 w-full">
            <ProfileHeading />
            <div className="mt-8 md:mt-4">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
